<Project Sdk="Beutl.Extensibility.Sdk/2.0.0-preview.8">

    <PropertyGroup>
        <PackageId>Beutl.Extensions.PsdTachie</PackageId>
        <Title>PSD立ち絵</Title>
        <Description>PSDファイルのレイヤーを切り替えて表示し、口パクと目パチを自動で行う立ち絵オブジェクトを追加します</Description>
        <PackageTags>psd,tachie,lipsync,character,立ち絵,口パク</PackageTags>
        <Version>0.1.0</Version>
        <AssemblyVersion>0.1.0.0</AssemblyVersion>
        <Authors>Yuto Terada</Authors>
        <BeutlAutoReferenceSourceGenerators>false</BeutlAutoReferenceSourceGenerators>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference
            Include="Beutl.Engine.SourceGenerators"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false"
            Version="2.0.0-preview.8"
            PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Beutl.Extensions.PsdTachie.Tests" />
    </ItemGroup>

</Project>
